const path = require('path');
const fs = require('fs');
const { CONFIG } = require('../config');
const { getWorkspaceRoot } = require('./backup');

/**
 * Write AI-generated content to DEVLOG.md
 * @param {string} content - AI-generated markdown content
 * @param {Object} sessionStats - Session statistics for header
 */
function writeLog(content, sessionStats) {
    const root = getWorkspaceRoot();
    
    if (!root) {
        throw new Error('No workspace folder open');
    }

    const logPath = path.join(root, CONFIG.LOG_FILENAME);
    const now = new Date();
    
    const dateStr = now.toLocaleDateString('en-US', { 
        weekday: 'long', 
        year: 'numeric', 
        month: 'long', 
        day: 'numeric' 
    });
    const timeStr = now.toLocaleTimeString('en-US', { 
        hour: '2-digit', 
        minute: '2-digit' 
    });

    const filesChanged = sessionStats.filesModified.size;
    const captures = sessionStats.saveCount;
    
    const entry = `\n---\n\n## 📝 Log: ${dateStr} at ${timeStr}\n\n**Session Stats:** ${captures} captures across ${filesChanged} files\n\n${content}\n\n*Generated by Auto-DevLog*\n`;

    if (!fs.existsSync(logPath)) {
        const header = `# Developer Log\n\nAutomated development journal powered by Auto-DevLog.\n`;
        fs.writeFileSync(logPath, header + entry, 'utf8');
    } else {
        fs.appendFileSync(logPath, entry, 'utf8');
    }

    console.log(`[DevLog] Written to: ${logPath}`);
}

module.exports = {
    writeLog
};
