const path = require('path');
const fs = require('fs');

// Load environment variables from .env file
function loadEnv() {
    try {
        const envPath = path.join(__dirname, '..', '..', '.env');
        if (fs.existsSync(envPath)) {
            require('dotenv').config({ path: envPath });
        }
    } catch (error) {
        console.log('[DevLog] No .env file found, using defaults');
    }
}
loadEnv();

/**
 * Extension configuration loaded from .env with fallback defaults
 */
const CONFIG = {
    // API Settings
    GEMINI_API_KEY: process.env.GEMINI_API_KEY || 'PASTE_KEY_HERE',
    GEMINI_MODEL: process.env.GEMINI_MODEL || 'gemini-2.5-flash',
    API_TIMEOUT: parseInt(process.env.API_TIMEOUT) || 15000,

    // Timing Settings
    DEBOUNCE_DELAY: parseInt(process.env.DEBOUNCE_DELAY) || 3000,
    INACTIVITY_CHECK_INTERVAL: parseInt(process.env.INACTIVITY_CHECK_INTERVAL) || 60000,
    INACTIVITY_THRESHOLD: parseInt(process.env.INACTIVITY_THRESHOLD) || 900000,

    // Truncation Settings
    MAX_CONTENT_LENGTH: parseInt(process.env.MAX_CONTENT_LENGTH) || 30000,
    TRUNCATE_HEAD: parseInt(process.env.TRUNCATE_HEAD) || 10000,
    TRUNCATE_TAIL: parseInt(process.env.TRUNCATE_TAIL) || 5000,

    // Paths
    BACKUP_PATH: '.vscode/devlog-temp.json',
    LOG_FILENAME: 'DEVLOG.md'
};

/**
 * Gemini API URL constructed from model config
 */
const GEMINI_API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${CONFIG.GEMINI_MODEL}:generateContent`;

/**
 * AI System Prompt with anti-spam rules for UI code
 */
const AI_SYSTEM_PROMPT = `You are a Senior Technical Writer & DevOps Engineer creating a high-quality "Developer Log" from raw code changes.

### 🎯 GOAL
Transform raw file diffs into a professional, structured, and insightful development update. The audience is fellow developers and project managers.

### 🚫 RESTRICTIONS
1.  **NO** line-by-line code recitals (e.g., "Changed line 40 to X").
2.  **NO** listing imports or minor formatting changes unless they are critical.
3.  **NO** vague statements like "Updated file.js". Always explain *WHAT* and *WHY*.
4.  **UI CHANGES**: Do NOT list CSS/HTML details. Summarize visual changes (e.g., "Redesigned Dashboard with dark mode support").

### ✍️ WRITING STYLE
-   **Tone**: Professional, technical, concise, and active.
-   **Format**: Clean Markdown with emojis for category headers.
-   **Detail**: Focus on **Logic**, **Architecture**, **Data Flow**, and **Key Decisions**.

### 📝 OUTPUT FORMAT
Please organize the log into the following categories (omit empty categories):

#### ✨ New Features
*   [Feature Name]: Description of capability and implementation details.

#### 🐛 Bug Fixes
*   [Component]: Description of the specific bug and the fix applied.

#### ♻️ Refactoring & Updates
*   [Scope]: Details on code structure improvements, cleanup, or config changes.

#### 🏗️ Architecture / System
*   [Topic]: High-level design changes or important architectural notes.

---
*Generated by Auto-DevLog*`;

module.exports = {
    CONFIG,
    GEMINI_API_URL,
    AI_SYSTEM_PROMPT
};
